agentscope-ai/agentscope

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md

Add the following templates for issues and pull requests.
- issue
- bug report
- feature request
- pr

Add templates for issues and pull requests

---

notebook/conversation.ipynb

add jupyter for conversation

---

README.md

minor improvement for the links and position of "Tutorial"'s first appearance

---

setup.py

---
Set version limits for requirements
---

[Hot fix]Set version limits for requirements

---

README.md

Fix tutorial/API_doc links in readme 

---

src/agentscope/_init.py
src/agentscope/_runtime.py
src/agentscope/constants.py
src/agentscope/file_manager.py
src/agentscope/utils/tools.py

---
---
When calling `agentscope.init` function, save the runtime information in the root directory. Specifically, the information will be stored in a file named `.config`, which includes a dictionary with the following fields:
```
{
"project": "xxx",
"name": "xxx",
"timestamp": "xxx",
"id": "xxx",
}
```

Saving runtime configuration in root directory automatically

---

examples/werewolf/prompt.py

refine prompt for werewolf game

---

README.md

- Add arXiv paper into README.md

Add arXiv paper into README.md

---

docs/sphinx_doc/source/tutorial/103-example.md
docs/sphinx_doc/source/tutorial/105-logging.md
docs/sphinx_doc/source/tutorial/201-agent.md

fix minor example bugs and typos

---

README.md

---
Slight modification on README.md 
---
As title says.

Slight modification on README.md 

---

setup.py

Update description in `setup.py`

Update description in `setup.py`

---

setup.py

---
Preparation for the first release
---

[Release] Preparation for the first release

---

README.md

Add news in README.md

---

.github/workflows/unittest.yml
src/agentscope/service/execute_code/exec_python.py
src/agentscope/utils/common.py
tests/execute_python_code_test.py
tests/logger_test.py

---
Add win & mac OS support
---
1. Add UT in mac & win OS.
2. Fix related bug in win & mac OS.

Add win & macos support

---

src/agentscope/utils/logging_utils.py
src/agentscope/web/studio/studio.py
src/agentscope/web/studio/utils.py

Stop using thread.name as uid, use a thread local value as uid

---

src/agentscope/agents/dict_dialog_agent.py
src/agentscope/models/model.py
src/agentscope/utils/logging_utils.py

[Hot Fix]Fix text display in logger

---

src/agentscope/models/openai_model.py

[Hotfix] remove checking response.status_code

---

src/agentscope/models/dashscope_model.py

add preprocess for roles for qwen

---

src/agentscope/models/dashscope_model.py
src/agentscope/models/openai_model.py

[Hot Fix]Optimize error messages of ModelWrapper

---

src/agentscope/service/__init__.py

---
---
- Add missing function ServiceFactory export

Fix export issue: Add missing function ServiceFactory export

---

examples/conversation_basic/README.md

Fix bug in basic conversation example.

Fix bug in basic conversation example

---

README.md
README_ZH.md

[Hotfix] Fix hyperlinks

---

src/agentscope/agents/text_to_image_agent.py
src/agentscope/utils/common.py

Fix the text_to_image_agent failure when accepting None input

---

src/agentscope/web/studio/utils.py

Avoid unnecessary logging when importing studio, the logging is like `Backend MacOSX is interactive backend. Turning interactive mode on.`

[HotFix] Avoid unnecessary logging in studio

---

README.md
README_ZH.md
examples/game_werewolf/configs/model_configs.json
src/agentscope/agents/user_agent.py
src/agentscope/utils/logging_utils.py
src/agentscope/web/README.md

Add AS studio in README

---

src/agentscope/pipelines/pipeline.py

Add attr `participants` to pipeline

---

README.md
README_ZH.md
docs/sphinx_doc/en/source/agentscope.agents.rst
docs/sphinx_doc/zh_CN/source/agentscope.agents.rst
examples/conversation_with_react_agent/code/conversation_with_react_agent.py
examples/conversation_with_react_agent/main.ipynb
src/agentscope/agents/__init__.py
src/agentscope/agents/react_agent.py
src/agentscope/models/post_model.py

- Add ReAct agent
- Add an example for conversation with react agent

Add a ReAct agent and an example conversation with this agent. 

---

examples/distributed/user_proxy_agent.py
src/agentscope/agents/rpc_agent.py
src/agentscope/models/__init__.py
src/agentscope/pipelines/functional.py
src/agentscope/utils/monitor.py
tests/monitor_test.py
tests/rpc_agent_test.py

fix mypy ignore pattern

---

src/agentscope/_version.py

Update version number into 0.0.3 in GitHub.

Update version number.

---

docs/sphinx_doc/en/source/tutorial/206-prompt.md
docs/sphinx_doc/zh_CN/source/tutorial/206-prompt.md
examples/conversation_with_react_agent/main.ipynb
examples/distributed_basic/README.md
examples/distributed_debate/README.md
examples/distributed_search/README.md
examples/game_gomoku/code/gomoku_agent.py
src/agentscope/agents/dict_dialog_agent.py
src/agentscope/agents/react_agent.py
src/agentscope/message.py
src/agentscope/models/__init__.py
src/agentscope/models/dashscope_model.py
src/agentscope/models/gemini_model.py
src/agentscope/models/model.py
src/agentscope/models/ollama_model.py
src/agentscope/models/openai_model.py
src/agentscope/models/post_model.py
src/agentscope/models/response.py
tests/format_test.py
tests/model_test.py
tests/prompt_engine_test.py
tests/web_digest_test.py

1. update format function for `DashScopeChatWrapper`, `OllamaGenerationWrapper` and `GeminiChatWrapper`
2. move model response related classes into a single file
3. update docs
1. update prompt for `ReActAgent` to adapt to qwen-max
2. add a re-correct processing in `ReActAgent`
3. add a `ResponseParser` to handle the conversation from text to dict and list
4. add a `ResponseParsingError` to enable self-correct operation

Update ReActAgent for qwen and other models

---

src/agentscope/models/dashscope_model.py

Fix Dashscope total_token calculation

---

README.md
README_ZH.md
scripts/README.md
scripts/ollama/model_config.json

- fix #141 
- update readme.md for v0.0.3.

Fix typos in scripts and update README.md

---

src/agentscope/agents/rpc_agent.py
src/agentscope/file_manager.py
src/agentscope/message.py
src/agentscope/utils/logging_utils.py
src/agentscope/utils/monitor.py
tests/rpc_agent_test.py

When multiple agents in the same agent server are called simultaneously, they will try to create the same directory at the same time and cause errors.

Fix "File exists error" when multiple agents are called at the same time

---

src/agentscope/models/ollama_model.py

Allow the response from ollama doesn't have token counts.

[HOTFIX] Allow the response from ollama doesn't have token counts.

---

examples/game_werewolf/werewolf_utils.py
src/agentscope/web/README.md
src/agentscope/web/studio/utils.py

Add checking reset before user input in studio

---

.github/workflows/unittest.yml

fix macos version error

---

src/agentscope/web/workstation/workflow_dag.py
src/agentscope/web/workstation/workflow_node.py

Make workflow compiler return code string

---

.github/workflows/sphinx_docs.yml
docs/sphinx_doc/build_sphinx_doc.sh
docs/sphinx_doc/en/source/conf.py
docs/sphinx_doc/en/source/index.rst
docs/sphinx_doc/template/module.rst_t
docs/sphinx_doc/template/package.rst_t
docs/sphinx_doc/zh_CN/source/conf.py
docs/sphinx_doc/zh_CN/source/index.rst
src/agentscope/agents/dict_dialog_agent.py
src/agentscope/message.py
src/agentscope/msghub.py
src/agentscope/prompt.py

1. Generate `.rst` for each `.py` file automatically
2. Add the `.py` files in the first-level directory to API doc, such as `message.py` and `prompt.py`
3. Add `__init__` method into API doc

[DOC] Generate .rst for each .py file and add __init__ method into docs

---

README.md
README_ZH.md

[HOTFIX] Fix typo in 0.0.4 README_ZH

---

README.md
README_ZH.md

Preview: https://github.com/rayrayraykk/AgentScope/tree/banner

Add banner

---

examples/distributed_basic/README.md

[DOC] Update distributed_basic/README.md

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/custom.md
.github/ISSUE_TEMPLATE/feature_request.md

update issues temp

---

README.md
README_ZH.md

Do not merge until the survey is published, thanks!

Add survey 

---

src/agentscope/web/workstation/workflow_node.py

support dalle on workstation

---

README_ZH.md

删除markdown “-”.md

---

README.md
README_ZH.md

add news for website maintenance

---

examples/game_werewolf/prompt.py
examples/game_werewolf/werewolf.py

As the title says. Fix Q1 and Q2 of the issue #243

Fix typo and prompt for game_werewolf

---

examples/game_werewolf/README.md

This is a cleaned-up version of the `game_werewolf_README` branch; the purpose of which is to reformat and update the README file of the example `game_werewolf`.

the cleaned-up version of game_werewolf_README branch

---

README.md
examples/game_werewolf/README.md

Add a demo video in README.md of both the repo and werewolf game. 

Add a demo video in README.md of both the repo and werewolf game

---

examples/game_werewolf/prompt.py
examples/game_werewolf/werewolf_utils.py

1. change "speak" to "vote" when in the voting phase
2. change "Player" to "P[p]layer" for the Regular Expression

refine prompt for werewolf games

---

examples/swe_agent/main.ipynb

---
---
Update tested models for the example swe_agent.

Update tested model list in SWE agent example

---

setup.py

[Hotfix] Add bs4 in setup.py to digest searched web pages

---

setup.py
tests/dashscope_services_test.py

[Hotfix] Fix the error in unittest.

---

README.md
README_ZH.md
setup.py

[HOTFIX] Fix error in setup.py and update doc

---

README.md
docs/sphinx_doc/en/source/tutorial/104-usecase.md
docs/sphinx_doc/zh_CN/source/tutorial/104-usecase.md
examples/game_werewolf/README.md
examples/game_werewolf/werewolf.py

1. update the video in the readme
2. update the tutorial about game werewolf
3. update the readme of game werewolf
4. reform codes in werewolf.py

Update files related to game werewolf

---

docs/sphinx_doc/en/source/tutorial/104-usecase.md
docs/sphinx_doc/zh_CN/source/tutorial/104-usecase.md

[Hotfix] Fix link issue in tutorial

---

docs/sphinx_doc/en/source/index.rst
docs/sphinx_doc/en/source/tutorial/209-prompt_opt.md
docs/sphinx_doc/en/source/tutorial/main.md
docs/sphinx_doc/zh_CN/source/index.rst
docs/sphinx_doc/zh_CN/source/tutorial/209-prompt_opt.md
docs/sphinx_doc/zh_CN/source/tutorial/main.md

- Fix error in tutorial related to system prompt optimization

[HOTFIX] Fix error in tutorial related to system prompt optimization

---

README.md
README_ZH.md

update news: Workstation back online

---

examples/conversation_with_RAG_agents/README.md

Fix env typo

---

examples/llm_based_algorithm/README.md

Initial commit for the research project on LLM-based algorithms.

Initial commit for research on LLM-based algorithms

---

src/agentscope/service/service_toolkit.py

If it is json(str) convert to json(dict)

---

README.md
README_ZH.md
src/agentscope/message.py

---
---
The variable `_colored_name` can not be found  when invoking `log_msg`  to print a msg. 

fix msg colored name and enlarge demo image of streaming mode

---

.github/workflows/pre-commit.yml
.github/workflows/sphinx_docs.yml
.github/workflows/unittest.yml

Add cname & update setuptools version

---

src/agentscope/studio/static/js/index.js

[Hot Fix] Fixed script loaded check function in Studio

---

scripts/flask_modelscope/setup_ms_service.py
scripts/flask_transformers/setup_hf_service.py
src/agentscope/models/post_model.py
src/agentscope/utils/tools.py

1. change keys from `inputs` to `messages` in flask services  since the default `messages_key` has been changed to `messages`
2. remove `reform_dialogue` in flask services since it has been done before calling post

Fix bugs for flask

---

src/agentscope/utils/tools.py

---
---
Modify the faulty logic of the original `check_port` function.

[Hot Fix]Fix bugs for check_port

---

README.md

change the format of my name as per my id/passport
---
---

Update name in README.md

---

src/agentscope/manager/_model.py

Fix the bug that `_ModelConfig` can't be serialized during `fork` or `spawn`.

[Hot Fix] Fix `_ModelConfig` state get and set

---

src/agentscope/service/execute_code/exec_shell.py

As described in the title.
To solve #411 

Add security checking for the service function execute_shell_command

---

src/agentscope/models/response.py

[Hot Fix] Fix text field of ModelResponse when using stream mode

---

README.md
README_ZH.md
setup.py
src/agentscope/_version.py
src/agentscope/manager/_manager.py
tests/manager_test.py

Update the version number to v 0.1.0

Preparation for version v0.1.0

---

src/agentscope/models/ollama_model.py
tests/format_test.py

---
---
According to issue #441 
Change role from `system` to `user`

Change the role to "user" in format function of ollama chat model

---

src/agentscope/agents/react_agent.py

---
---
1. Fixed a minor bug where the "max_iters" parameter was not used in the for loop.

minor fix on max_iters parameter passing bug

---

src/agentscope/server/servicer.py

fix Changed 'reply' function call to use argument unpacking for improved argument handling in distributed code.

fix Changed 'reply' function call to use argument unpacking for improved argument handling in distributed code.

---

examples/distributed_debate/distributed_debate.py

Fix the distributed debate example.

[Hot Fix] Fix the distributed debate example.

---

src/agentscope/web/workstation/workflow_dag.py

Fix UTF-8 issues on workstation

---

src/agentscope/parsers/regex_tagged_content_parser.py

---
---
Delete unnecessary logs

Delete unnecessary logs

---

src/agentscope/rag/knowledge.py
src/agentscope/rag/llama_index_knowledge.py

---
---
* add a hash field to `RetrievedChunk` to help deduplication

add hash to retrieved result (`RetrievedChunk`)

---

.github/workflows/sphinx_docs.yml

Fix bug in tutorial building

---

.github/workflows/sphinx_docs.yml

Fix the bug in tutorial building

---

.github/workflows/publish-pypi.yml
src/agentscope/_version.py

Update version and add GitHub publish workflow

---

.github/workflows/publish-pypi.yml

[HOTFIX] Add dependencies in GitHub workflow

---

.github/workflows/publish-pypi.yml

Change the command used in the workflow to avoid ignoring html files

---

.github/workflows/publish-pypi.yml

Fix dependency error in workflow

---

README.md
README_JA.md
README_ZH.md
applications/multisource_rag_app/README.md

---
---
Update the QR code of the DingTalk group

[Quick fix] Update QR code

---

src/agentscope/service/mcp_manager.py

hotfix MCP

---

src/agentscope/service/multi_modality/dashscope_services.py

[HOTFIX] Fix bug in `dashscope_text_to_image` service

---

docs/tutorial/en/source/tutorial/MCP.py
docs/tutorial/zh_CN/source/tutorial/MCP.py
src/agentscope/service/mcp_manager.py
tests/custom/as_mcp_server.py
tests/service_toolkit_test.py

Fix STDIO mcp and add ut

---

src/agentscope/agents/_react_agent_v2.py
src/agentscope/models/dashscope_model.py
src/agentscope/studio/static/js/dashboard-detail-dialogue.js
tests/formatter_test.py

1. Support message displaying in AgentScope Studio
2. Allow the ReActAgentV2 to return message without calling the `generate_response` function

[HOTFIX] Fix bugs in studio and ReActAgentV2

---

README.md
README_JA.md
README_ZH.md
src/agentscope/_version.py

Update version for releasing v0.1.3 in Pypi

---

README_JA.md
README_ZH.md

[HOTFIX] Fix MCP url in README.md

---

docs/tutorial/en/source/tutorial/hook.py
docs/tutorial/zh_CN/source/tutorial/hook.py
src/agentscope/agents/_agent.py
src/agentscope/models/model.py
tests/hook_test.py

Fixed a design issue where hooks were incorrectly implemented at the class level. This PR introduces a distinction between instance-level and class-level hooks to ensure proper hook isolation and management.

Add object-level and class-level hooks

---

src/agentscope/service/mcp_manager.py
tests/service_toolkit_test.py

Fix mcp result

---

src/agentscope/service/mcp_manager.py

Hello. I found a typo and corrected it.
ModelContextProtocal -> ModelContextProtocol
Have a nice day

Fix :: Typo

---

src/agentscope/_version.py

Update the version to `0.1.5dev` for modelscope demo

Update version to 0.1.5dev

---

applications/multisource_rag_app/README.md
applications/multisource_rag_app/requirements.txt
applications/multisource_rag_app/src/as_scripts/setup_server.sh
applications/multisource_rag_app/src/configs/as_config/as_knowledge_configs/as_es_knowledge_update_config.json
applications/multisource_rag_app/src/configs/as_config/as_knowledge_configs/knowledge_config.json
applications/multisource_rag_app/src/copilot_app.py
docs/tutorial/en/source/conf.py
docs/tutorial/zh_CN/source/conf.py

---
---
* Add skipping process of images (in `conf.py`) when generating text only tutorial
* Update knowledge configs and env variables in the application
Related to https://github.com/modelscope/agentscope/issues/588

Fix rag application document path

---

applications/multisource_rag_app/src/async_model/async_dashscope.py
docs/tutorial/en/source/tutorial/hook.py
docs/tutorial/en/source/tutorial/structured_output.py
docs/tutorial/zh_CN/source/tutorial/hook.py
docs/tutorial/zh_CN/source/tutorial/structured_output.py
src/agentscope/agents/_agent.py
src/agentscope/agents/_react_agent_v2.py
src/agentscope/models/anthropic_model.py
src/agentscope/models/dashscope_model.py
src/agentscope/models/openai_model.py
src/agentscope/rpc/rpc_meta.py
src/agentscope/service/service_toolkit.py
tests/hook_test.py
tests/service_toolkit_test.py

1. Refactor service toolkit with Pydantic rather than parsing from scratch
2. Support structured output in ReActV2 agent
3. Fix the bug that `pre-reply` hook makes the parameters of the reply function immutable.

Support structured output in ReActV2 agent

---

README.md
README_JA.md
README_ZH.md

Update README.md to trigger the GitHub workflow

---

README.md
README_JA.md
README_ZH.md

[HOTFIX] Add contact in README.md

---

src/agentscope/agents/_react_agent.py
src/agentscope/message/block.py

[HOTFIX] Fix the bug in ReAct agent

---

README.md
README_JA.md
README_ZH.md

---
---
This PR updates the `README.md` to include a link to more detailed usage examples. The changes will help users find and understand how to use the MCP Tool more effectively.

docs(READMEs): update readme for mcp usage

---

src/agentscope/logging.py

[Hotfix] Fix msg.id not in _PREFIX_DICT

---

.github/workflows/publish-pypi.yml

[Hotfix] Fix error in pypi workflow

---

setup.py

[Hotfix] Fix the error in setup.py for v0.1

---

setup.py
src/agentscope/_version.py
src/agentscope/memory/_mem0_long_term_memory.py

1.0.1
- Add packaging into dependency
- Update version into 1.0.2
- Update the version of mcp library to be ">=1.13"

Add the missing dependencies; update version; update mcp version

---

docs/tutorial/en/src/task_studio.py
docs/tutorial/zh_CN/src/task_studio.py

1.0.2
Fix the studio-related error in the tutorial

[HOTFIX] Fix the studio-related error in the tutorial

---

docs/tutorial/en/src/task_plan.py
docs/tutorial/zh_CN/src/task_plan.py
src/agentscope/_version.py
src/agentscope/agent/_react_agent.py
src/agentscope/plan/_plan_notebook.py
tests/plan_test.py

1.0.2
Make the list_tool function sync

[HOTFIX] Fix the bug in the plan module

---

setup.py

`aioitertools` and `json5` are repeatedly declared in minimal_requires.

Remove some duplicated requirements

---

examples/functionality/plan/main_agent_managed_plan.py
examples/react_agent/main.py
src/agentscope/_version.py
src/agentscope/agent/_react_agent.py

1.0.3
Fix the bug in ReActAgent class

[HOTFIX] Fix the bug in ReActAgent class
