.github/workflows/sphinx_docs.yml, docs/README.md, docs/sphinx_doc/Makefile, docs/sphinx_doc/make.bat, docs/sphinx_doc/requirements.txt, docs/sphinx_doc/source/agentscope.agents.rst, docs/sphinx_doc/source/agentscope.configs.rst, docs/sphinx_doc/source/agentscope.memory.rst, docs/sphinx_doc/source/agentscope.models.rst, docs/sphinx_doc/source/agentscope.pipelines.rst, docs/sphinx_doc/source/agentscope.rpc.rst, docs/sphinx_doc/source/agentscope.rst, docs/sphinx_doc/source/agentscope.service.code.rst, docs/sphinx_doc/source/agentscope.service.file.rst, docs/sphinx_doc/source/agentscope.service.retrieval.rst, docs/sphinx_doc/source/agentscope.service.rst, docs/sphinx_doc/source/agentscope.service.sql_query.rst, docs/sphinx_doc/source/agentscope.service.text_processing.rst, docs/sphinx_doc/source/agentscope.service.web_search.rst, docs/sphinx_doc/source/agentscope.utils.rst, docs/sphinx_doc/source/agentscope.web_ui.rst, docs/sphinx_doc/source/conf.py, docs/sphinx_doc/source/index.rst, docs/sphinx_doc/source/tutorial/main.md, setup.py
---
name: [DOC] add API reference documentation
---
1. add sphinx doc scripts
2. add README on how to build the doc
3. add a GitHub workflow to build the doc automatically
=> [DOC] add API reference documentation

src/agentscope/agents/__init__.py
=> [hotfix] Fix missing UserAgent

src/agentscope/agents/rpc_agent.py, src/agentscope/message.py, src/agentscope/rpc/__init__.py, src/agentscope/rpc/rpc_agent_client.py
---
name: Fix import errors in RPC related modules
---
Fixed the bug that RPC related modules throw `ModuleNotFoundError` under default installation conditions
=> [hot fix] Fix import errors in RPC related modules

README.md, docs/sphinx_doc/source/tutorial/207-monitor.md, docs/sphinx_doc/source/tutorial/301-community.md
---
name: Update monitor tutorial and readme
---
1. update the tutorial on the monitor module
2. update links and QR Code in readme 
=> [DOC] Update monitor tutorial and readme

README.md, docs/sphinx_doc/source/index.rst, docs/sphinx_doc/source/tutorial/101-installation.md, docs/sphinx_doc/source/tutorial/104-usecase.md, docs/sphinx_doc/source/tutorial/301-community.md, notebook/conversation.ipynb, setup.py
=> change hyperlink to ms

README.md, docs/sphinx_doc/source/tutorial/201-agent.md, docs/sphinx_doc/source/tutorial/204-service.md, src/agentscope/agents/dict_dialog_agent.py, src/agentscope/models/model.py
=> [Hot fix]Fix parse_func and fault_handler of ModelWrapper

src/agentscope/service/execute_code/exec_python.py
=> Fix module `resource` not available in win

src/agentscope/service/service_factory.py
1. Move ServiceFactory into `agentscope.service.ServiceFactory`
2. Check if all arguments don't have default values.
=> Fix bug in service_factory

docs/sphinx_doc/en/source/tutorial/201-agent.md, docs/sphinx_doc/zh_CN/source/tutorial_zh/201-agent.md, src/agentscope/agents/agent.py, src/agentscope/agents/dialog_agent.py, src/agentscope/agents/dict_dialog_agent.py, src/agentscope/agents/text_to_image_agent.py, src/agentscope/agents/user_agent.py, src/agentscope/memory/memory.py, src/agentscope/memory/temporary_memory.py, src/agentscope/prompt.py, src/agentscope/service/web_search/search.py, tests/rpc_agent_test.py
- Fix the error when `self.memory` is `None` in `reply` function. 
- Disable the default value of `model_config_name` of built-in agents, so that a model must be provided when using agent.
=> Fix error in agent when `use_memory` is `False`

src/agentscope/agents/dict_dialog_agent.py
Bug: The returned dictionary-format response should be turned into string before feeding into memory.
=> [HotFix] Fix bug in dict_dialog_agent

README.md, docs/sphinx_doc/en/source/tutorial/206-prompt.md, docs/sphinx_doc/en/source/tutorial/main.md, docs/sphinx_doc/zh_CN/source/tutorial/206-prompt.md, examples/conversation_self_organizing/auto-discussion.py, examples/conversation_with_langchain/conversation_with_langchain.py, examples/conversation_with_mentions/main.py, examples/distributed/distributed_debate.py, examples/game_werewolf/werewolf.py, examples/game_werewolf/werewolf_utils.py, src/agentscope/agents/dialog_agent.py, src/agentscope/agents/dict_dialog_agent.py, src/agentscope/agents/rpc_agent.py, src/agentscope/agents/text_to_image_agent.py, src/agentscope/agents/user_agent.py, src/agentscope/message.py, src/agentscope/models/dashscope_model.py, src/agentscope/models/gemini_model.py, src/agentscope/models/model.py, src/agentscope/models/ollama_model.py, src/agentscope/models/openai_model.py, src/agentscope/models/post_model.py, src/agentscope/prompt.py, src/agentscope/service/text_processing/summarization.py, src/agentscope/utils/logging_utils.py, tests/format_test.py, tests/memory_test.py, tests/model_test.py, tests/retrieval_from_list_test.py, tests/rpc_agent_test.py
- Support more model APIs in our examples without any adaptation work.
- Add `role` field in `Msg` class
- Provide a basic prompt strategy for all chat and generation API wrappers in their `format` function
- Change how prompt is constructed in built-in agents (Using `format` function)
- Update tutorial
- I'm not sure if we should desperate `prompt engine` module. Especially if we want to add prompt shrinking strategies in the future. 
- To accommodate the current versions, the `role` field current use `assistant` as default value and give a warning to remind users to fill this argument. 
- The `preprocess` function of `DashScopeChatWrapper` is retained and can work with `format` function together.
=> Fix bug in PromptEngine and provide prompt construction strategy for most chat and generation APIs

src/agentscope/agents/dict_dialog_agent.py, src/agentscope/models/dashscope_model.py, src/agentscope/models/gemini_model.py, src/agentscope/models/ollama_model.py, src/agentscope/models/openai_model.py, src/agentscope/models/post_model.py, src/agentscope/utils/tools.py
We cannot directly convert content to string by `str(content)` or `json.dumps(content)`
- `str(content)`: the converted string cannot be loaded by `json.loads` API. When we want LLMs to generate JSON format response, if we convert their past response to prompt by `str(content)`, LLMs may learn this format so that their future response cannot be loaded by `json.loads`. 
- `json.dumps(content)`: if `content` is a string, it will add extra double quotes.
A function convert content to string according to its type. 
Use this function in model wrappers' format function. 
=> [HOTFIX] Create a new function to convert content to string. 

docs/sphinx_doc/zh_CN/source/tutorial/104-usecase.md
原文：
更多细节和高阶永达，比如用POST API配置本地模型，可以参考[关于模型](https://modelscope.github.io/agentscope/zh_CN/tutorial/203-model.html)。
应该为：更多细节和高阶用法
=> 📃 docs: 文档词语错误：永达->用法

setup.py, src/agentscope/service/service_factory.py
1. `docstring_parser` is used in ServiceFactory, so we move it into mini_requires
2. add check and warning for necessary packages. 
=> Fix bug in requiring necessary packages

src/agentscope/agents/agent.py, src/agentscope/rpc/__init__.py, tests/agent_test.py
Add `agent_id` field to `AgentBase`, used to support message center and rpc agent server(#94 ).
The current `agent_id` is generated based on the following rules: `{agent_class_name}_{uuid}`
=> Add agent_id for each agent instance

setup.py, src/agentscope/_version.py
The current version 0.0.2 on PyPI has a bug that causes the distributed examples to fail completely. Therefore, it is necessary to update the version on PyPI to 0.0.3, and then update the version in the GitHub repository to 0.0.4-alpha.
We need to update the installation to `pip install agentscope --pre` in our docs to avoid updating version number frequently, especially when there are bugs in PyPi version. 
=> Update version to 0.0.4-alpha

setup.py, src/agentscope/service/__init__.py, src/agentscope/service/web_search/arxiv.py, tests/web_search_test.py
Add `arxiv_search` function to support searching in arxiv.
=> Add arxiv_search service function

src/agentscope/models/gemini_model.py
By this way, developers can set more parameters for `genai.configure()` in the model configuration as follows:
```python
{
"model_type": "gemini_chat",
"config_name": "xxx",
"api_key": "xxx",                # or pass by env variable.
"transport": "rest", 
}
```
=> [HOTFIX] Support gemini.configure setting in model configuration

src/agentscope/models/openai_model.py, src/agentscope/models/post_model.py
The safety system of OpenAI is rigorous, some simple prompts may be rejected. e.g. "Big explosion"
=> [Hot Fix] Raise error when user's request is rejected by OpenAI safety system

src/agentscope/parsers/code_block_parser.py
Fix the typos in parser module.
=> 【HOTFIX】Fix the typos in parser module

src/agentscope/memory/memory.py, src/agentscope/memory/temporary_memory.py, src/agentscope/message.py, tests/memory_test.py, tests/msghub_test.py
---
name: Fix memory loading error
---
Fix the error reported in #194 
The reason of this error is the temporary memory did not ensure the loaded content to be in message types in AS. Thus, this PR make the following changes to fix the issue:
1. When exporting the memory, use the `serialize` function provided in `message.py` instead of `json.dump`, and use `deserialize` instead of `json.load` when export/load memory from files.
2. When adding new pieces of message or dict into memory, manually check if they are Msg/Tht
=> [Hotfix] Fix memory loading error

docs/sphinx_doc/en/source/tutorial/206-prompt.md, docs/sphinx_doc/zh_CN/source/tutorial/206-prompt.md, src/agentscope/models/ollama_model.py, tests/format_test.py
In Ollama chat API, still, the roles of messages should be alternative (user and assistant). 
=> [HOTFIX] Update prompt strategy in Ollama chat API.

examples/conversation_basic/README.md, examples/conversation_self_organizing/README.md, examples/conversation_with_mentions/README.md
---
---
Added README file for `conversation_self_organizing`
=> Added README file for `conversation_self_organizing`

src/agentscope/models/litellm_model.py, src/agentscope/models/ollama_model.py
As the title says, within the react agent, it will pass "...{index}. {function_name} ..." to format method as system prompt, which will occur error in the string's format method. 
=> [HOTFIX] Fix bug in the format method of ollama and litellm

examples/conversation_with_RAG_agents/README.md
---
name: Add version specification for the RAG example
about: 
---
As reported in https://github.com/modelscope/agentscope/issues/245 , the code splitter in Llamaindex does not compatible with the lattest tree-sitter package. So we add specific version requirement for the RAG example.
=> [Hotfix] add version specification for the RAG example

src/agentscope/server/servicer.py
Fix ImportError `No module named 'expiringdict'`, when `import agentscope`
=> [Hot Fix] Fix import error when import agentscope

src/agentscope/_init.py, tests/rpc_agent_test.py
As the title says. Fix #259 and add test cases.
=> [Hot Fix] Fix the bug that the save_dir is not effective

src/agentscope/utils/logging_utils.py, tests/logger_test.py
- `logger.chat` cannot display special tags normally. (e.g. html labels and special tags begin with "<")
- In current version, we use the color label in loguru to display message with colored names, which will be mixed with labels within name and content
- We display the color by special tags in terminal, e.g. \033[90m
- To avoid saving the special tags (\033[90m) in files, we call logger.log twice (Lines 131-132, 143-144). The first time we display message in terminal with special tags, the second time we save this messages into files without these special tags.
=> [HOTFIX] Fix the bug in loguru that cannot display special tags

setup.py, src/agentscope/rag/llama_index_knowledge.py, tests/knowledge_test.py
---
name: Add unit test for LlamaIndexKnowledge
---
* remove ImportErrorReporter in the rag module, to avoid errors happened in typing check
* adding a unit test for the LlamaIndexKnowledge, to ensure related packages has been installed correctly
* fixed llamaindex version to a older one, aligned with the example
=> [Hotfix] Add unit test and fix import error of LlamaIndexKnowledge

docs/sphinx_doc/zh_CN/source/tutorial/208-distribute.md
=> fix(typo): update 208-distribute.md

docs/sphinx_doc/en/source/index.rst, docs/sphinx_doc/zh_CN/source/index.rst
=> [HOTFIX] Fix the error that cannot find rag in tutorial

src/agentscope/studio/static/css/workstation.css, src/agentscope/studio/static/js/workstation.js, src/agentscope/studio/templates/workstation.html
=> Add step mode for each examples in workstation

src/agentscope/agents/user_agent.py, src/agentscope/logging.py
---
name: Fix gradio displaying user message twice
about: bug-fixing
---
The current as_gradio displays the user input message on the left hand side. To prevent this:
* rename the `disable_studio` parameter of `_chat` to  `disable_gradio` to avoid ambiguity;
* set `disable_gradio=True` in UserAgent.speak .
Before fixing:
After fixing:
=> [Hotfix] Fix gradio displaying user message twice

src/agentscope/studio/static/js/workstation.js
Fix display bug in AgentScope workstation for group nodes. Specifically, when there are multiple levels of nested nodes, hide the nodes below first, then hide the node above two levels, and then open the upper node. The hidden nodes below will still be displayed, as shown in the figure.
For unhiding, it should be determined whether the child node's `contentBox` is marked as hidden to determine whether to unhide it.
=> Fix display bug in workstation for group nodes

src/agentscope/agents/dict_dialog_agent.py
- Fix the bug in DictDialogAgent
=> [HOTFIX] Fix bug in DictDialogAgent

src/agentscope/agents/react_agent.py
Fix the bug in react agent that prints the message twice when there is a response parsing error
=> [HOTFIX] Fix the duplicated printing in react agent.

examples/distributed_debate/user_proxy_agent.py, src/agentscope/agents/agent.py, src/agentscope/agents/rpc_agent.py, src/agentscope/logging.py, src/agentscope/msghub.py, tests/rpc_agent_test.py
- This PR is the pre-work of serialization/deserialization
- Unify the message related typing in AgentScope into Msg rather than dict. 
@qbc2016 This PR has changed the logic within the function `log_gradio`, please check if the change is correct.
=> Unify message related typing in AgentScope into Msg rather than dict

src/agentscope/logging.py
As the title said, avoid to raise error in logger when not initialized by `agentscope.init`
=> Allow user to initialize agent without calling agentscope.init

src/agentscope/studio/static/js/workstation.js, src/agentscope/web/workstation/workflow_dag.py, src/agentscope/web/workstation/workflow_node.py
Now after copying html config and saving as xxx.json, one can run `as_gradio xxx.json`.
=> Support running as_gradio for html configs

README.md, README_ZH.md, examples/conversation_with_router_agent/README.md, examples/conversation_with_router_agent/main.py, examples/conversation_with_router_agent/router_agent.py
Add a demonstration example for router agent.
=> Add example for router agent

README.md, README_ZH.md, examples/distributed_conversation/README.md
=> [Hotfix] Fix hyperlinks for online workstation in readme

src/agentscope/manager/_manager.py, tests/custom/test_model_config.json, tests/rpc_agent_test.py
=> [Hot Fix] Fix `ModelManager` not initialize in distributed mode

src/agentscope/rag/__init__.py, src/agentscope/rag/knowledge_bank.py, tests/knowledge_test.py
=> [HotFix] lazy load llama-index-knownledge

.github/workflows/unittest.yml, docs/sphinx_doc/en/source/tutorial/104-usecase.md, docs/sphinx_doc/zh_CN/source/tutorial/104-usecase.md, docs/sphinx_doc/zh_CN/source/tutorial/209-gui.md, src/agentscope/models/post_model.py, tests/minimal.py
=> [Hot Fix] Add test for minimal dependencies

README.md, README_ZH.md
=> Remove something

src/agentscope/models/response.py
Fix the issue of `ModelResponse.text` content duplication in stream mode.
=> [Hot Fix] Fix stream text

src/agentscope/manager/_file.py, src/agentscope/rag/llama_index_knowledge.py
---
---
* fix the bug that Llamaindex files are saved in directory related to run id.
* fix file manager embedding bug
=> [Hotfix] minor fix on embedding related bugs

src/agentscope/models/dashscope_model.py, src/agentscope/models/litellm_model.py, src/agentscope/models/model.py, src/agentscope/models/ollama_model.py, src/agentscope/models/openai_model.py, src/agentscope/models/post_model.py, src/agentscope/models/yi_model.py, src/agentscope/models/zhipu_model.py, tests/format_test.py
I found the current format strategy leads to misunderstanding. 
For example, the following formatted message will be inserted a system prompt automatically by the API provider, and the LLM will refuse to act as the new role, e.g. "Friday"
```python
prompt = [
{"role": "user", "content": "You're a helpful assistant named Friday\\n#Conversation History\\nuser:Hello!"}
]
```
With the above prompt, Qwen-max responses "I'm Qwen, not Friday." 
We check if there is a system prompt, and put it at the beginning of the formatted prompt.
```python
prompt = [
{"role": "system", "content": "You're a helpful assistant named Friday"},
{"role": "user", "content": "#Conversation History\\nuser:Hello!"}
]
```
=> [HOTFIX] Fix the error in format function by adding system message

src/agentscope/parsers/json_object_parser.py
---
---
fix the bug issued in [issue  #466](https://github.com/modelscope/agentscope/issues/466)
add a test function `test_markdownjsondictparser_with_nested_schema` in `tests/parser_test.py`
=> use model_dump instead of dict(*) in MarkdownJsonDictParse

setup.py, src/agentscope/__init__.py, src/agentscope/logging.py, src/agentscope/models/model.py, src/agentscope/service/__init__.py, src/agentscope/service/browser/web_browser.py, src/agentscope/tokens.py, tests/tokens_test.py
1. Add a new tokens module in AgentScope to handle token related events
2. Support to count tokens for OpenAI, DashScope, Gemini and HuggingFace models
3. Support to register token counting functions
A more elegant way to register token counting functions for different models
=> Support token counting for OpenAI, DashScope, Gemini and HuggingFace models

src/agentscope/_version.py, src/agentscope/models/dashscope_model.py, tests/dashscope_test.py
When using multiple dashscope API keys, the line `dashcsope.api_key = self.api_key` will cover each other, and finally there is only one valid api key.
=> [HOTFIX] Fix the error when using multiple dashscope api keys

src/agentscope/logging.py, src/agentscope/service/service_toolkit.py, tests/service_toolkit_test.py
The current logging will save all loggings in one line
The service toolkit cannot recognize array type.
Allow users to call `agentscope.init` repeatly.
@pan-x-c Please ensure the modification works in distribution mode
=> [HOTFIX] Fix the bug in service toolkit and logging

src/agentscope/utils/common.py
This is a bug that I came across during playing with the [conversation_with_web_browser_agent](https://github.com/modelscope/agentscope/tree/main/examples/conversation_with_web_browser_agent) example on **Windows**. 
The bug was that OpenAI cannot access the local URL path because it is passed to the API as URL but not base64 format. This is caused by [this line](https://github.com/modelscope/agentscope/blob/9aa404a7e5384ebcd6bc7d6d7b9029b7f24b16c0/src/agentscope/utils/common.py#L298). urllib somehow parse the local path "C:\Users\xx" with C as the scheme, so the first branch of the if is executed, which means the file is checked as a web URL.
Not a good enough solution for now to add an exists check before the scheme check, but please feel free to discuss a more proper way.
=> Fix a bug in checking local or remote file on Windows

docs/sphinx_doc/en/source/tutorial/203-model.md, docs/sphinx_doc/zh_CN/source/tutorial/203-model.md, src/agentscope/__init__.py, src/agentscope/_init.py, src/agentscope/manager/_model.py, src/agentscope/models/__init__.py, src/agentscope/models/dashscope_model.py, src/agentscope/models/model.py, src/agentscope/models/openai_model.py, src/agentscope/models/post_model.py, tests/model_test.py
The previous automatic model wrapper registration requires users to import their model wrapper class (even if they are not using it). 
1. Remove th automatic model wrapper registration
2. Instead, provide a `register_model_wrapper_class` function in agentscope module
```python
import agentscope
agentscope.register_model_wrapper_class(my_new_model_wrapper_class, exist_ok=False)
```
=> Support explicit model wrapper registration

examples/conversation_with_codeact_agent/codeact_agent.py
---
name: Fix typos in codeact_agent.py
---
Fix typos in codeact_agent.py
=> Fix typos in codeact_agent.py

docs/tutorial/en/source/tutorial/MCP.py, docs/tutorial/zh_CN/source/tutorial/MCP.py, src/agentscope/service/mcp_manager.py, tests/custom/as_mcp_server.py
When we run the MCP toolkit with `uvloop`, an error might happen, which is caused due to the conflicts between `uvloop` and `nest_asyncio` (they both affected `asyncio`, and have their management policy with event loop). So we will not include `nest_asyncio.apply()` in our source file. 
```bash
Exception in thread Thread-4 (run):
Traceback (most recent call last):
File "/Users/raykkk/miniconda3/envs/ws2/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
self.run()
File "/Users/raykkk/miniconda3/envs/ws2/lib/python3.10/threading.py", line 953, in run
self._target(*self._args, **self._kwargs)
File "/Users/raykkk/miniconda3/envs/ws2/lib/python3.10/site-packages/uvicorn/server.py", line 66, in run
return asyncio.run(self.serve(sockets=sockets))
File …
```
=> [Hotfix] Support MCP run with uvloop

README.md, docs/ROADMAP.md
This PR fixes two issues:
1.  **MCP Tutorial Link:** Corrects the capitalization in the MCP tutorial link found in the News section of the README.
*   Incorrect: `https://doc.agentscope.io/build_tutorial/mcp.html`
*   Correct: `https://doc.agentscope.io/build_tutorial/MCP.html`
2.  **Roadmap Status:** Updates the status markers (✅, 🚧, 📝) in `docs/ROADMAP.md` for Tool Calling and RAG features to reflect the current implementation state based on code review.
=> Fix MCP link and update roadmap status

src/agentscope/agents/_react_agent_v2.py, src/agentscope/formatters/_dashscope_formatter.py
Fix the bug that 
1. The content field must be a string in Dashscope tools API
2. The printing of the response message 
=> Fix the error within DashScopeFormatter and ReActAgentV2

setup.py
Tighten MCP library version dependency to exclude 1.10.x due to unknown compatibility issues
=> [Hotfix]fix mcp version

README.md, README_JA.md, README_ZH.md, src/agentscope/_version.py
=> Update AgentScope Logo; update version into v0.1.6;

README.md
=> Update README.md with migration news

src/agentscope/model/_dashscope_model.py
v1.0.0
Add `base_http_api_url` in DashScopeChatModel's constructor
=> Add `base_http_api_url` in DashScopeChatModel's constructor

docs/tutorial/en/src/task_mcp.py, docs/tutorial/zh_CN/src/task_mcp.py, examples/agent_deep_research/deep_research_agent.py, src/agentscope/mcp/_http_stateful_client.py, src/agentscope/mcp/_stdio_stateful_client.py
=> Refine tutorial for multi mcp stateful clients

docs/tutorial/en/src/task_model.py, docs/tutorial/en/src/task_pipeline.py, docs/tutorial/zh_CN/src/task_model.py, docs/tutorial/zh_CN/src/task_pipeline.py, examples/agent_deep_research/README.md, examples/react_agent/README.md, examples/workflows/multiagent_conversation/README.md, examples/workflows/multiagent_debate/README.md, src/agentscope/tool/_multi_modality/_dashscope_tools.py, src/agentscope/tool/_multi_modality/_openai_tools.py
- Add tutorial for fanout pipeline
- Fix some docstring format
=> Add tutorial for fanout pipeline

src/agentscope/_logging.py
- Added a check in the setup_logger function to validate that the provided level is one of "INFO", "DEBUG","WARNING", "ERROR", or "CRITICAL".
- If an invalid level is provided, a ValueError is raised with a clear error message indicating the valid options.
=> feat: improve logging setup by validating level

src/agentscope/message/msg.py, tests/logger_test.py
… logger.info
AgentScope Version : v0
[Console Error Log]
File "/Users/syrianazh/Desktop/pyWorkSpace/agentscope/src/agentscope/message/msg.py", line 175, in __init__
logger.chat(self)
^^^^^^^^^^^
AttributeError: 'Logger' object has no attribute 'chat'
[Path]
https://github.com/agentscope-ai/agentscope/blob/v0/src/agentscope/message/msg.py#L175
[Cause]
I wanted to do some MCP test with logger print,  When I Init a ReActAgent with config parameter [verbose:true] and registry a [MCP service_toolkit], and then i calling agent(x) speak to agent. The calling step will execute to https://github.com/agentscope-ai/agentscope/blob/v0/src/agentscope/agents/_react_agent.py#L157 , in _reasoning(self) fuctions will new init a Msg use ReActAgent verbose param value assign to Msg echo param. And then …
=> [Lightweight Bugfix] Fix when init Msg class, error calling function logger.chat

src/agentscope/agent/_react_agent.py
Modify the ReActAgent's self._agent_control to avoid being assigned as False when the mode is "both".
self._agent_control = long_term_memory and long_term_memory_mode in [
"agent_control",
"both",
]
=> fix bug of self._agent_control

docs/tutorial/en/src/task_state.py, docs/tutorial/zh_CN/src/task_state.py, examples/functionality/session_with_sqlite/main.py, examples/functionality/session_with_sqlite/sqlite_session.py, src/agentscope/session/_json_session.py, src/agentscope/session/_session_base.py, tests/session_test.py
1.0.2
- Remove the argument session_id, so that one JSONSession object can handle multiple sessions
- Modify the example accordingly
=> Remove the argument session_id from the constructor to support different sessions

src/agentscope/model/_dashscope_model.py
- 将 enable_thinking 判空条件由简单布尔判断改为非 None 判断
- 避免 enable_thinking 为 False 时跳过赋值的问题
- 确保当 kwargs 中无 enable_thinking 时正确添加对应参数
=> fix(model): 修复DashScopeChatModel enable_thinking 不起作用
